# Generated by Django 4.1.7 on 2023-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=10)),
                ('lon', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('obs', models.CharField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
